services:
  demo-database:
    image: postgres:alpine
    container_name: flowers
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flowershop

